import { AiFillStar } from "react-icons/ai";

{
   const data = [
      {
        img:  "https://www.acrats.com/uploads/media_1823138968567787.jpg",
        title: "Product 1",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        price: "€10.000",
        category: "Category 1",
      },
      {
        img:  "https://www.acrats.com/uploads/media_1823138968567787.jpg",
        title: "Product 2",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        price: "€10.000",
        category: "Category 1",
      },
      {
        img:  "https://www.acrats.com/uploads/media_1823138968567787.jpg",
        title: "Product 3",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        price: "€10.000",
        category: "Category 1",
      },
      {
        img:  "https://www.acrats.com/uploads/media_1823138968567787.jpg",
        title: "Product 4",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        price: "€10.000",
        category: "Category 2",
      },
      {
        img:  "https://www.acrats.com/uploads/media_1823138968567787.jpg",
        title: "Product 5",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        price: "€10.000",
        category: "Category 2",
      },
      {
        img:  "https://www.acrats.com/uploads/media_1823138968567787.jpg",
        title: "Product 6",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        price: "€10.000",
        category: "Category 2",
      },
      {
        img:  "https://www.acrats.com/uploads/media_1823138968567787.jpg",
        title: "Product 7",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        price: "€10.000",
        category: "Category 3",
      },
      {
        img:  "https://www.acrats.com/uploads/media_1823138968567787.jpg",
        title: "Product 8",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        price: "€10.000",
        category: "Category 3",
      },
      {
        img:  "https://www.acrats.com/uploads/media_1823138968567787.jpg",
        title: "Product 8",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        price: "€10.000",
        category: "Category 3",
      },
      {
        img:  "https://www.acrats.com/uploads/media_1823138968567787.jpg",
        title: "Product 9",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        price: "€10.000",
        category: "Category 4",
      },
      {
        img:  "https://www.acrats.com/uploads/media_1823138968567787.jpg",
        title: "Product 10",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        price: "€10.000",
        category: "Category 4",
      },
      {
        img:  "https://www.acrats.com/uploads/media_1823138968567787.jpg",
        title: "Product 11",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        price: "€10.000",
        category: "Category 4",
      },
      {
        img:  "https://www.acrats.com/uploads/media_1823138968567787.jpg",
        title: "Product 12",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        price: "€10.000",
        category: "Category 5",
      },
      {
        img:  "https://www.acrats.com/uploads/media_1823138968567787.jpg",
        title: "Product 12",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        price: "€10.000",
        category: "Category 5",
      },
      {
        img:  "https://www.acrats.com/uploads/media_1823138968567787.jpg",
        title: "Product 12",
        star: <AiFillStar className="rating-star" />,
        reviews: "(123 reviews)",
        price: "€10.000",
        category: "Category 5",
      },
      ];}